# Generated by Django 6.0.2 on 2026-02-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
