# Generated by Django 6.0.2 on 2026-02-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active_participants_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='active_participants_usage',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees_usage',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='event',
            name='helpers_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='helpers_usage',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
