# Generated by Django 6.0.2 on 2026-02-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_active_participants_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='application_role',
            field=models.CharField(choices=[('attendee', 'Audience Ticket'), ('active_participant', 'Active Participant'), ('helper_team', 'Helper Team')], default='attendee', max_length=30),
        ),
    ]
