# Generated by Django 6.0.2 on 2026-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_application_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attendance_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
