# Generated by Django 6.0.2 on 2026-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_attendance_marked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If private, event is only accessible via direct link'),
        ),
    ]
