# Generated by Django 6.0.2 on 2026-03-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_event_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active_participant_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of active participant emails'),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of guest emails for private events'),
        ),
    ]
