# Generated by Django 6.0.2 on 2026-03-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_privateeventpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='security_answer_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_question',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset', 'Reset'), ('delete_account', 'Delete Account')], max_length=20),
        ),
    ]
