# Generated by Django 6.0.2 on 2026-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_promocode_payment_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
