# Generated by Django 6.0.2 on 2026-03-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_eventcategory_profile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.tickettype'),
        ),
    ]
