# Generated by Django 6.0.2 on 2026-03-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_loginthrottle_securityauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageHeroPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(max_length=80)),
                ('headline', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('chip_one', models.CharField(blank=True, max_length=40)),
                ('chip_two', models.CharField(blank=True, max_length=40)),
                ('chip_three', models.CharField(blank=True, max_length=40)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='homepage_hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
