# Generated by Django 6.0.2 on 2026-03-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_advertisement_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementsettings',
            name='slot_count',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
