# Generated by Django 6.0.2 on 2026-03-25 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_advertisement_slots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('rotation_seconds', models.PositiveSmallIntegerField(default=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisement_slot_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot_index'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementSlotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_items', to='core.eventadvertisement')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.advertisementslot')),
            ],
            options={
                'ordering': ['slot', 'position', 'id'],
                'unique_together': {('slot', 'advertisement')},
            },
        ),
    ]
