# Generated by Django 6.0.2 on 2026-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_advertisement_slot_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementslot',
            name='size',
            field=models.CharField(choices=[('compact', 'Compact'), ('standard', 'Standard'), ('large', 'Large'), ('wide', 'Wide')], default='standard', max_length=12),
        ),
    ]
