# Generated by Django 6.0.2 on 2026-03-25 16:37

from django.db import migrations, models
from django.db.models import F


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_advertisement_slot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementslot',
            name='design',
            field=models.CharField(choices=[('classic', 'Classic'), ('glass', 'Glass'), ('bold', 'Bold'), ('soft', 'Soft')], default='classic', max_length=12),
        ),
        migrations.AlterField(
            model_name='advertisementslot',
            name='slot_index',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('core', 'AdvertisementSlot')
            .objects.filter(slot_index__gt=0)
            .update(slot_index=F('slot_index') - 1),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
