# Generated by ChatGPT on 2026-03-25

from django.db import migrations


def normalize_slot_indexes(apps, schema_editor):
    Slot = apps.get_model("core", "AdvertisementSlot")
    slots = list(Slot.objects.order_by("slot_index", "id"))
    if not slots:
        return
    for slot in slots:
        slot.slot_index = slot.slot_index + 1000
        slot.save(update_fields=["slot_index"])
    for index, slot in enumerate(slots):
        slot.slot_index = index
        slot.save(update_fields=["slot_index"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_advertisement_slot_design"),
    ]

    operations = [
        migrations.RunPython(normalize_slot_indexes, migrations.RunPython.noop),
    ]
