from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("events/", views.public_events, name="public_events"),
    path("newsletter-subscribe/", views.newsletter_subscribe, name="newsletter_subscribe"),
    path("auth/", views.auth_page, name="auth_page"),
    path("login/", views.login_submit, name="login_submit"),
    path("register/send-otp/", views.register_send_otp, name="register_send_otp"),
    path("verify-otp/", views.verify_otp, name="verify_otp"),
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("forgot-password/send-otp/", views.forgot_password_send_otp, name="forgot_password_send_otp"),
    path("reset-password/", views.reset_password, name="reset_password"),
    path("logout/", views.logout_submit, name="logout_submit"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("browse-events/", views.browse_events, name="browse_events"),
    path("events/<int:event_id>/", views.event_detail, name="event_detail"),
    path("book/<int:event_id>/", views.book_event, name="book_event"),
    path("payment/<int:booking_id>/", views.payment_page, name="payment_page"),
    path("payment/<int:booking_id>/pay/", views.payment_pay, name="payment_pay"),
    path("booking-success/<int:booking_id>/", views.booking_success, name="booking_success"),
    path("my-bookings/", views.my_bookings, name="my_bookings"),
    path("my-bookings/<int:booking_id>/ticket-pdf/", views.download_ticket_pdf, name="download_ticket_pdf"),
    path("ticket-lookup/", views.ticket_lookup, name="ticket_lookup"),
    path("ticket-scan/<str:token>/", views.ticket_qr_scan, name="ticket_qr_scan"),
    path("my-bookings/<int:booking_id>/cancel/", views.cancel_booking, name="cancel_booking"),
    path("event-history/", views.event_history, name="event_history"),
    path("invoices/", views.invoices, name="invoices"),
    path("invoices/<int:booking_id>/download/", views.download_invoice, name="download_invoice"),
    path("profile/", views.profile_view, name="profile"),
    path("settings/", views.settings_view, name="settings"),
    path("settings/password/", views.settings_password, name="settings_password"),
    path("settings/security-question/", views.settings_security_question, name="settings_security_question"),
    path("settings/preferences/", views.settings_preferences, name="settings_preferences"),
    path("notifications/", views.notifications_view, name="notifications"),
    path(
        "notifications/mark-all-read/",
        views.notifications_mark_all_read,
        name="notifications_mark_all_read",
    ),
    path("notifications/<int:notification_id>/read/", views.notification_mark_read, name="notification_mark_read"),
    path("support/", views.support_view, name="support"),
    path("my-events/", views.my_events, name="my_events"),
    path(
        "my-events/<int:event_id>/participants/excel/",
        views.download_event_participants_excel,
        name="download_event_participants_excel",
    ),
    path("my-events/new/", views.new_event, name="new_event"),
    path("my-events/<int:event_id>/edit/", views.edit_event, name="edit_event"),
    path("my-events/<int:event_id>/delete/", views.delete_event, name="delete_event"),
    path(
        "my-events/private-payment/<int:payment_id>/",
        views.private_event_payment_page,
        name="private_event_payment_page",
    ),
    path(
        "my-events/private-payment/<int:payment_id>/pay/",
        views.private_event_payment_pay,
        name="private_event_payment_pay",
    ),
    path("organizer-bookings/", views.organizer_bookings, name="organizer_bookings"),
    path("account/delete/", views.delete_account, name="delete_account"),
]
