"""
URL Configuration - Website ke sabhi routes yahan define hote hain.
Har URL map karta hai ek view function ko.
Example: /dashboard/ -> dashboard view
"""

from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("events/", views.public_events, name="public_events"),
    path("newsletter-subscribe/", views.newsletter_subscribe, name="newsletter_subscribe"),
    path("auth/roles/", views.auth_role_page, name="auth_role_page"),
    path("auth/", views.auth_page, name="auth_page"),
    path("login/", views.login_submit, name="login_submit"),
    path("auth/social/google/", views.social_login_google, name="social_login_google"),
    path("auth/social/github/", views.social_login_github, name="social_login_github"),
    path("auth/2fa/verify/", views.verify_2fa, name="verify_2fa"),
    path("register/send-otp/", views.register_send_otp, name="register_send_otp"),
    path("verify-otp/", views.verify_otp, name="verify_otp"),
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("forgot-password/send-otp/", views.forgot_password_send_otp, name="forgot_password_send_otp"),
    path("reset-password/", views.reset_password, name="reset_password"),
    path("logout/", views.logout_submit, name="logout_submit"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("browse-events/", views.browse_events, name="browse_events"),
    path("events/<int:event_id>/", views.event_detail, name="event_detail"),
    path("book/<int:event_id>/", views.book_event, name="book_event"),
    path("payment/<int:booking_id>/", views.payment_page, name="payment_page"),
    path("payment/<int:booking_id>/pay/", views.payment_pay, name="payment_pay"),
    path("payment/<int:booking_id>/verify/", views.payment_verify, name="payment_verify"),
    path("booking-success/<int:booking_id>/", views.booking_success, name="booking_success"),
    path("my-bookings/", views.my_bookings, name="my_bookings"),
    path("my-bookings/<int:booking_id>/ticket-pdf/", views.download_ticket_pdf, name="download_ticket_pdf"),
    path("ticket-lookup/", views.ticket_lookup, name="ticket_lookup"),
    path("ticket-recheck/", views.ticket_recheck, name="ticket_recheck"),
    path("ticket-scan/<str:token>/", views.ticket_qr_scan, name="ticket_qr_scan"),
    path("my-bookings/<int:booking_id>/cancel/", views.cancel_booking, name="cancel_booking"),
    path("event-history/", views.event_history, name="event_history"),
    path("payment-history/", views.payment_history, name="payment_history"),
    path("payment-history/export/csv/", views.payment_history_export_csv, name="payment_history_export_csv"),
    path("payment-history/export/pdf/", views.payment_history_export_pdf, name="payment_history_export_pdf"),
    path("invoices/", views.invoices, name="invoices"),
    path("invoices/<int:booking_id>/download/", views.download_invoice, name="download_invoice"),
    path("complete-profile/", views.complete_profile, name="complete_profile"),
    path("profile/", views.profile_view, name="profile"),
    path("settings/", views.settings_view, name="settings"),
    path("settings/password/", views.settings_password, name="settings_password"),
    path("settings/password/send-otp/", views.settings_password_send_otp, name="settings_password_send_otp"),
    path("settings/security-question/", views.settings_security_question, name="settings_security_question"),
    path(
        "settings/security-question/send-otp/",
        views.settings_security_send_otp,
        name="settings_security_send_otp",
    ),
    path("settings/preferences/", views.settings_preferences, name="settings_preferences"),
    path("settings/email-verification/", views.verify_email, name="verify_email"),
    path("verify-email-confirm/", views.verify_email_confirm, name="verify_email_confirm"),
    path("settings/2fa/setup/", views.setup_2fa, name="setup_2fa"),
    path("settings/2fa/enable/", views.enable_2fa, name="enable_2fa"),
    path("settings/2fa/disable/", views.disable_2fa, name="disable_2fa"),
    path("notifications/", views.notifications_view, name="notifications"),
    path(
        "notifications/mark-all-read/",
        views.notifications_mark_all_read,
        name="notifications_mark_all_read",
    ),
    path("notifications/<int:notification_id>/read/", views.notification_mark_read, name="notification_mark_read"),
    path("support/", views.support_view, name="support"),
    path("support/chat/start/", views.support_chat_start, name="support_chat_start"),
    path(
        "support/chat/<int:conversation_id>/message/",
        views.support_chat_message,
        name="support_chat_message",
    ),
    path(
        "support/chat/<int:conversation_id>/handoff/",
        views.support_chat_handoff,
        name="support_chat_handoff",
    ),
    path("my-events/", views.my_events, name="my_events"),
    path(
        "my-events/<int:event_id>/participants/excel/",
        views.download_event_participants_excel,
        name="download_event_participants_excel",
    ),
    path("my-events/new/", views.new_event, name="new_event"),
    path("my-events/<int:event_id>/edit/", views.edit_event, name="edit_event"),
    path("my-events/<int:event_id>/delete/", views.delete_event, name="delete_event"),
    path("my-events/<int:event_id>/schedule/add/", views.event_schedule_add, name="event_schedule_add"),
    path("my-events/schedule/<int:schedule_id>/edit/", views.event_schedule_edit, name="event_schedule_edit"),
    path(
        "my-events/schedule/<int:schedule_id>/delete/",
        views.event_schedule_delete,
        name="event_schedule_delete",
    ),
    path("my-events/<int:event_id>/gallery/add/", views.event_gallery_add, name="event_gallery_add"),
    path("my-events/gallery/<int:gallery_id>/delete/", views.event_gallery_delete, name="event_gallery_delete"),
    path(
        "my-events/private-payment/<int:payment_id>/",
        views.private_event_payment_page,
        name="private_event_payment_page",
    ),
    path(
        "my-events/private-payment/<int:payment_id>/pay/",
        views.private_event_payment_pay,
        name="private_event_payment_pay",
    ),
    path(
        "my-events/private-payment/<int:payment_id>/verify/",
        views.private_event_payment_verify,
        name="private_event_payment_verify",
    ),
    path("organizer-bookings/", views.organizer_bookings, name="organizer_bookings"),
    path(
        "organizer-bookings/export/csv/",
        views.organizer_bookings_export_csv,
        name="organizer_bookings_export_csv",
    ),
    path(
        "organizer-bookings/export/pdf/",
        views.organizer_bookings_export_pdf,
        name="organizer_bookings_export_pdf",
    ),
    path("platform-admin/dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("platform-admin/events/", views.admin_events, name="admin_events"),
    path("platform-admin/advertisements/", views.admin_advertisements, name="admin_advertisements"),
    path(
        "platform-admin/advertisements/settings/",
        views.admin_advertisement_settings_update,
        name="admin_advertisement_settings_update",
    ),
    path(
        "platform-admin/advertisements/slots/",
        views.admin_advertisement_slots_update,
        name="admin_advertisement_slots_update",
    ),
    path(
        "platform-admin/advertisements/bulk/",
        views.admin_advertisements_bulk,
        name="admin_advertisements_bulk",
    ),
    path(
        "platform-admin/advertisements/<int:ad_id>/update/",
        views.admin_advertisement_update,
        name="admin_advertisement_update",
    ),
    path("platform-admin/users/", views.admin_users, name="admin_users"),
    path("platform-admin/bookings/", views.admin_bookings, name="admin_bookings"),
    path("platform-admin/payments/", views.admin_payments, name="admin_payments"),
    path("platform-admin/support/", views.admin_support, name="admin_support"),
    path(
        "platform-admin/support/<int:ticket_id>/",
        views.admin_support_detail,
        name="admin_support_detail",
    ),
    path(
        "platform-admin/support/<int:ticket_id>/draft-ai-reply/",
        views.admin_generate_support_reply,
        name="admin_generate_support_reply",
    ),
    path(
        "platform-admin/support/<int:ticket_id>/send-reply/",
        views.admin_send_support_reply,
        name="admin_send_support_reply",
    ),
    path(
        "platform-admin/support/<int:ticket_id>/resolve/",
        views.admin_resolve_ticket,
        name="admin_resolve_ticket",
    ),
    path("account/delete/", views.delete_account, name="delete_account"),
]
